### PR TITLE
Completed UI Exercise

### PR DESCRIPTION
**Pull request by AsimKhan2019**
Completed the UI Exercise. Applied all the functions and operations for the OOP School Library console application. 
The application performs the following operations 

Get the list of Books 
Get the list of People 
Creates a new Student or Teacher 
Creates a new Book 
Creates a new Rental 
Get the list of Rentals 
Exit the application

Added 2 files to the project 

app. rb - Contains all the operations required for the application to perform
main. rb - Calls the app functions whenever called to perform the operations 

P.S. The ids for the Student and Teacher are generated, and for getting the list of rentals, the right ID must be entered in order to get the rental information. Do not enter 0 or 1 but the actual person ID. 

I am also trying to store permissions data into the variable, but not storing it as I am already handling the permission value by default as the linters point out. So kindly please ignore that scenario. The permission is stored by default.

### CODE REVIEW

**Review by zainsadaqat — CHANGES_REQUESTED** [review]
# Required Changes 🔁
# Hello @AsimKhan2019  😄 

You're doing a great job on your project. We're proud of you. Good job so far! 

There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
  ✅  Correct use of Github Flow
  ✅  No linter errors
  ✅  Descriptive Pull Request

## Required Changes ♻️

- [x] During creating a rental, when we try to input a wrong value the app crashes. It should not crash the app Rather it should show us a warning that the bad input or something similar. Please fix this 👍 

Screenshot 2022-09-30 at 4 45 24 PM


_Check the comments under the review._




## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding! 👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by AsimKhan2019** [comment]
@zainsadaqat Thank you for the review. I will try to fix this. How did you create the error? I would like to know this for my own knowledge.

**Review by KayLemba — APPROVED** [review]
# STATUS: APPROVED :green_circle: :clap: 

Hello  @AsimKhan2019    , 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

HIGHLIGHTS:

- Your project is professional 
- Your repo is professional 
- Well structured files 
- No linter errors 
- Nice UI design


Now you can merge this branch and move on :1st_place_medal: 
Happy Coding cheers 🥇 💯 

well-1

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by AsimKhan2019** [comment]
@KayLemba Thank you for the approval

**Pull request merged**
